// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Tambahkan helper kecil untuk memastikan environment variable tersedia.
// Kalau belum ada, helper ini melempar error yang jelas;
// kalau ada, hasilnya bertipe string
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("DATABASE_URL belum diatur");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
